
#define IFACE_UNTITLED_PROJECT					NSLocalizedString(@"Untitled Project", @"")
#define IFACE_MY_PROJECT						NSLocalizedString(@"My Project", @"")

#define IFACE_TOOLBAR_LOG						NSLocalizedString(@"View log", @"")
#define IFACE_TOOLBAR_LOG_PALETTE_LABEL			NSLocalizedString(@"Log", @"")

#define IFACE_UPDATINGFILECOUNT					NSLocalizedString(@"Updating file count", @"")
#define IFACE_NOINPUTFILES						NSLocalizedString(@"Add files to process: drag or select", @"")
#define IFACE_NOTHINGSELECTED					NSLocalizedString(@"You have deselected all of your files", @"")
#define IFACE_SELECTED							NSLocalizedString(@"selected", @"")
#define IFACE_FILE								NSLocalizedString(@"file", @"")
#define IFACE_FILES								NSLocalizedString(@"files", @"")
#define IFACE_DIRECTORY							NSLocalizedString(@"directory", @"")
#define IFACE_DIRECTORIES						NSLocalizedString(@"directories", @"")
#define IFACE_CONTAINING						NSLocalizedString(@"containing", @"")
#define IFACE_VALIDFILE							NSLocalizedString(@"processable file", @"")
#define IFACE_VALIDFILES						NSLocalizedString(@"processable files", @"")
#define IFACE_AND								NSLocalizedString(@"and", @"")
#define IFACE_TOTALFILECOUNT					NSLocalizedString(@"Valid files", @"")
#define IFACE_PROCESSEDFILES					NSLocalizedString(@"Processed files", @"")
#define IFACE_ADDEDFILES						NSLocalizedString(@"Added files", @"")
#define IFACE_MODIFIEDFILES						NSLocalizedString(@"Modified files", @"")

#define IFACE_DEFAULTTEMPLATE					NSLocalizedString(@"Default template", @"")
#define IFACE_MODIFIED							NSLocalizedString(@"modified", @"")
#define IFACE_NOERRORS							NSLocalizedString(@"No errors", @"")

#define IFACE_SELECT							NSLocalizedString(@"Select", @"")

#define IFACE_COLLECTINGFILES					NSLocalizedString(@"Collecting files", @"")
#define IFACE_PARSINGFILES						NSLocalizedString(@"Parsing files", @"")
#define IFACE_CREATEINHERITANCERELATIONS		NSLocalizedString(@"Create inheritance relations", @"")
#define IFACE_CREATEINTERFACERELATIONS			NSLocalizedString(@"Create interface relations", @"")
#define IFACE_RESOLVESEEREFERENCES				NSLocalizedString(@"Resolving link references", @"")
#define IFACE_WRITINGFILES						NSLocalizedString(@"Writing files", @"")

#define IFACE_SAVECHANGESXSLT					NSLocalizedString(@"Save changes XSLT", @"")
#define IFACE_SAVECHANGESCSS					NSLocalizedString(@"Save changes CSS", @"")
#define IFACE_SAVE								NSLocalizedString(@"Save", @"")
#define IFACE_CANCEL							NSLocalizedString(@"Cancel", @"")
#define IFACE_DONTSAVE							NSLocalizedString(@"Don't save", @"")
#define IFACE_CLOSE								NSLocalizedString(@"Close", @"")

#define IFACE_NOTREGISTERED						NSLocalizedString(@"Not registered", @"")
#define IFACE_LIMITED							NSLocalizedString(@"In trial mode", @"")
#define IFACE_BUY								NSLocalizedString(@"Buy", @"")
#define IFACE_TRY								NSLocalizedString(@"Try", @"")
#define IFACE_REGISTER							NSLocalizedString(@"Register", @"")
//#define IFACE_TITLENOTREGISTERED				NSLocalizedString(@"RegistationTitleNotRegistered", @"")
//#define IFACE_TITLEREGISTERED					NSLocalizedString(@"RegistationTitleRegistered", @"")

#define IFACE_HINTCHOOSECLASSFILES				NSLocalizedString(@"Choose class files", @"")
#define IFACE_HINTCHOOSEOUTPUT					NSLocalizedString(@"Choose output directory", @"")
#define IFACE_HINTDEMOMODE						NSLocalizedString(@"Demo mode", @"")

#define IFACE_MENUBUY							NSLocalizedString(@"Buy VisDoc", @"")
#define IFACE_MENUREGISTER						NSLocalizedString(@"Register", @"")

#define IFACE_SAVECHANGESPROJECT_TITLE			NSLocalizedString(@"Do you want to save changes to", @"")
#define IFACE_SAVECHANGES_TITLE					NSLocalizedString(@"Do you want to save changes", @"")
#define IFACE_SAVECHANGESPROJECT_COMMENT		NSLocalizedString(@"If you don't save, your changes will be lost.", @"")
#define IFACE_REVERTPROJECT_TITLE				NSLocalizedString(@"Revert to saved version", @"")
#define IFACE_REVERTPROJECT_COMMENT				NSLocalizedString(@"Reverting will loose your current changes.", @"")
#define IFACE_REVERT							NSLocalizedString(@"Revert", @"")
#define IFACE_COULDNOTOPENPROJECT_TITLE			NSLocalizedString(@"Could not open project", @"")
#define IFACE_COULDNOTSAVEPROJECT_TITLE			NSLocalizedString(@"Could not save project", @"")
#define IFACE_OK								NSLocalizedString(@"OK", @"")

#define IFACE_PROCESSALLSELECTED				NSLocalizedString(@"Process all selected files", @"")
#define IFACE_ADDEDANDMODIFIEDONLY				NSLocalizedString(@"Process added and modified files only", @"")

#define IFACE_CLEARMENU							NSLocalizedString(@"Clear Menu", @"")

/* Log */
#define IFACE_LOG_STARTPROCESSING				NSLocalizedString(@"Start processing", @"")
#define IFACE_LOG_PROCESSEDFILES				NSLocalizedString(@"Processed files", @"")
#define IFACE_LOG_DUPLICATEFILES				NSLocalizedString(@"Duplicate files", @"")
#define IFACE_LOG_EXCLUDEDFILES					NSLocalizedString(@"Excluded files", @"")
#define IFACE_LOG_MISSINGREFERENCES				NSLocalizedString(@"Missing references", @"")
#define IFACE_LOG_INVALIDFILES					NSLocalizedString(@"Invalid files", @"")
#define IFACE_LOG_ADDEDFILES					NSLocalizedString(@"Added files", @"")
#define IFACE_LOG_REMOVEDFILES					NSLocalizedString(@"Removed files", @"")
#define IFACE_LOG_UPDATEDFILES					NSLocalizedString(@"Updated files", @"")
#define IFACE_LOG_MEMBER						NSLocalizedString(@"Member", @"")
#define IFACE_LOG_TAG							NSLocalizedString(@"Tag", @"")
#define IFACE_FILE_COUNT						NSLocalizedString(@"Total number of files", @"")
#define IFACE_LOG_FILESREAD						NSLocalizedString(@"Files read", @"")
#define IFACE_LOG_PROJECTOPENED					NSLocalizedString(@"Project opened", @"")
#define IFACE_LOG_AUTOMATICPROCESSING			NSLocalizedString(@"Automatic processing", @"")
#define IFACE_LOG_AUTOMATICPROCESSINGSTARTING	NSLocalizedString(@"Automatic processing starting", @"")
#define IFACE_LOG_PREVIOUSNOTFINISHEDYET		NSLocalizedString(@"Previous processing not finished yet.", @"")
#define IFACE_LOG_NOFILESTOPROCESS				NSLocalizedString(@"No files to process.", @"")
#define IFACE_LOG_NOVALIDOUTPUTDIRECTORY		NSLocalizedString(@"No valid output directory set.", @"")

